apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tgf1aki7m-go 
  janus-idp.io/tekton: tgf1aki7m-go
  backstage.io/kubernetes-id: tgf1aki7m-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tgf1aki7m-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  