apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tgf1aki7m-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tgf1aki7m-go 
  name: tgf1aki7m-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: tgf1aki7m-go 
